---
- name: Install Ansible with pip3.10
  ansible.builtin.pip:
    name: ansible
    executable: pip3.10
    extra_args: --user

- name: Remove old Ansible yum installation
  ansible.builtin.yum:
    name: ansible
    state: absent
  become: yes

- name: Refresh table of recently executed programs
  ansible.builtin.shell:
    cmd: hash -r
